version: "3.9"

networks:
  wargaming:

services:
  mysql:
    container_name: wargaming-mysql
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wargaming
      - MYSQL_USER=wargaming
      - MYSQL_PASSWORD=wargaming
      - TZ=Asia/Shanghai
    ports:
      - "3307:3306"
    networks:
      - wargaming

  redis:
    container_name: wargaming-redis
    image: "redis:latest"
    ports:
      - "6378:6379"
    command: ["redis-server", "--requirepass", "wargaming"]
    environment:
      - ALLOW_EMPTY_PASSWORD=no
    networks:
      - wargaming

  rabbitmq:
    container_name: wargaming-rabbitmq
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=wargaming
      - RABBITMQ_DEFAULT_PASS=wargaming
    networks:
      - wargaming

  consul:
    container_name: wargaming-consul
    image: hashicorp/consul:latest
    command: agent -dev -client=0.0.0.0
    ports:
      - "8500:8500"
      - "8300:8300"
      - "8301:8301"
      - "8302:8302"
      - "8600:8600/udp"
    networks:
      - wargaming

  jaeger:
    container_name: wargaming-jaeger
    image: "jaegertracing/all-in-one:latest"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "14268"
      - "14250:14250"
      - "6831:6831"
    networks:
      - wargaming
