// Code generated by Kitex v0.8.0. DO NOT EDIT.

package gameservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	game "wargaming/kitex_gen/game"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Match(ctx context.Context, req *game.MatchReq, callOptions ...callopt.Option) (r *game.MatchResp, err error)
	Move(ctx context.Context, req *game.MoveReq, callOptions ...callopt.Option) (r *game.MoveResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kGameServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kGameServiceClient struct {
	*kClient
}

func (p *kGameServiceClient) Match(ctx context.Context, req *game.MatchReq, callOptions ...callopt.Option) (r *game.MatchResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Match(ctx, req)
}

func (p *kGameServiceClient) Move(ctx context.Context, req *game.MoveReq, callOptions ...callopt.Option) (r *game.MoveResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Move(ctx, req)
}
