// Code generated by hertz generator.

package interact

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _interactMw() []app.HandlerFunc {
	// your code...
	return nil
}
