server:
  name: wargaming

jwt:
  accessSecret: MTAxNTkwMTg1Mw==
  accessExpire: 3600

mysql:
  addr: localhost:3307
  database: wargaming
  user: wargaming
  password: wargaming
  charset: utf8mb4

redis:
  addr: localhost:6378
  password: wargaming

rabbitmq:
  addr: 127.0.0.1:5672
  user: wargaming
  password: wargaming

consul:
  addr: localhost:8500

jaeger:
  addr: localhost:6831

services:
  api:
    name: api
    load-balance: false
    addr:
      - 172.20.242.130:10001
  user:
    name: user
    load-balance: false
    addr:
      - 172.20.242.130:10002

  game:
    name: interact
    load-balance: false
    addr:
      - 172.20.242.130:10003

  interact:
    name: game
    load-balance: false
    addr:
      - 172.20.242.130:10004