// Code generated by hertz generator.

package interact

import (
	"context"
	"wargaming/cmd/api/biz/pack"
	"wargaming/cmd/interact/biz/model/interact"
	"wargaming/cmd/interact/biz/ws"

	"github.com/cloudwego/hertz/pkg/app"
)

// Interact .
// @router /interact [GET]
func Interact(ctx context.Context, c *app.RequestContext) {

	var err error
	var req interact.InteractReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, err)
		return
	}

	ws.Interact(ctx, c, &req)
}
